.\" (C) Copyright 2015, Ross Gammon <rossgammon@mail.dk>,
.\"
.TH NC4TONC3 1 "22 Mar 2015"
.\"
.SH NAME
nc4tonc3 \- a program to convert a classic netCDF 4 file to netCDF 3 format
.SH SYNOPSIS
.B nc4tonc3
.RB [ \-h ]
.RB [ \-o ]
.RB [ \-\-chunk ]
.I netcdf4filename
.I netcdf3filename
.br
.SH DESCRIPTION
This manual page documents briefly the
.B nc4tonc3
command.
.PP
\fBnc4tonc3\fP is a program that converts a netCDF 4 file (in NETCDF4_CLASSIC format) to netCDF 3 format.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-h
Shows a summary of the available options.
.TP
.B \-o
Overwrite destination file (default is to raise an error if output file already exists).
.TP
.B \-\-quiet=(0|1)
If set to 1, don't print any diagnostic information.
.TP
.B \-\-format
Choose the netcdf3 format to use. NETCDF3_64BIT is used by default, or it can be set to NETCDF3_CLASSIC.
.TP
.B \-\-chunk=(integer)
The number of records along unlimited dimension to write at once. The default is 10. It is ignored if there is no unlimited dimension. If chunk=0, this means write all the data at once.
.SH SEE ALSO
.BR ncinfo (1),
.BR nc3tonc4 (1).
.br
.SH AUTHOR
This manual page was written by Ross Gammon <rossgammon@mail.dk> based on the options displayed by nc3tonc4 \-h.
