environment:
  CONDA_INSTALL_LOCN: C:\\Miniconda36-x64
  matrix:
    - TARGET_ARCH: x64
      NPY: 1.16
      PY: 3.6

    - TARGET_ARCH: x64
      NPY: 1.16
      PY: 3.7

platform:
  - x64

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Add path, activate `conda` and update conda.
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - cmd: conda update conda
  - cmd: conda config --remove channels defaults --force
  - cmd: conda config --add channels conda-forge --force
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: conda install conda-build vs2008_express_vc_python_patch
  - cmd: call setup_x64

  - cmd: conda create --name TEST python=%PY% numpy=%NPY% cython pip pytest hdf5 libnetcdf cftime
  - cmd: conda info --all
  - cmd: conda activate TEST

  - cmd: echo [options] > setup.cfg
  - cmd: echo [directories] >> setup.cfg
  - cmd: echo HDF5_libdir = %CONDA_PREFIX%\Library\lib >> setup.cfg
  - cmd: echo HDF5_incdir = %CONDA_PREFIX%\Library\include >> setup.cfg
  - cmd: echo netCDF4_libdir = %CONDA_PREFIX%\Library\lib >> setup.cfg
  - cmd: echo netCDF4_incdir = %CONDA_PREFIX%\Library\include >> setup.cfg

# Skip .NET project specific build phase.
build: off

test_script:
  - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  - set NO_NET=1
  - cd test && python run_all.py
