environment:
  PYTHON: "C:\\myminiconda3"
  matrix:
    - NPY: 1.17
      PY: 3.7

    - NPY: 1.17
      PY: 3.8

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Add path, activate `conda` and update conda.
  - set URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
  - curl -fsS -o miniconda3.exe %URL%
  - start /wait "" miniconda3.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%PYTHON%

  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - call %PYTHON%\Scripts\activate

  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda config --add channels conda-forge --force
  - set PYTHONUNBUFFERED=1
  - conda install conda-build vs2008_express_vc_python_patch
  - call setup_x64

  - conda create --name TEST python=%PY% numpy=%NPY% cython pip pytest hdf5 libnetcdf cftime
  - conda activate TEST

  - echo [options] > setup.cfg
  - echo [directories] >> setup.cfg
  - echo HDF5_libdir = %CONDA_PREFIX%\Library\lib >> setup.cfg
  - echo HDF5_incdir = %CONDA_PREFIX%\Library\include >> setup.cfg
  - echo netCDF4_libdir = %CONDA_PREFIX%\Library\lib >> setup.cfg
  - echo netCDF4_incdir = %CONDA_PREFIX%\Library\include >> setup.cfg

  - conda info --all
  - conda list

# Skip .NET project specific build phase.
build: off

test_script:
  - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
  - set NO_NET=1
  - cd test && python run_all.py
