name: linux-tests-mpi

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      shell: bash -l {0}
      env:
        MPI: 1
        CC: mpicc.mpich
        DEPENDS: "numpy>=1.10.0 cython>=0.21 setuptools>=18.0 mpi4py>=1.3.1 cftime"
        NETCDF_VERSION: 4.7.3
        PNETCDF_VERSION: 1.12.1
        NETCDF_DIR: $GITHUB_WORKSPACE/netcdf
      run: |
        sudo apt-get install mpich libmpich-dev libhdf5-mpich-dev
        # pick up nc-config here
        echo "${NETCDF_DIR}/bin" >> $GITHUB_PATH
        python -m pip install --upgrade pip setuptools
        python -m pip install ${DEPENDS}
        if [ $MPI -eq 1 ] ; then ci/build-parallel-netcdf.sh; fi
        python setup.py build
        python setup.py install

    - name: Run tests
      run: cd test && python run_all.py