name: windows

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        numpy-version: [1.17, 1.19]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }} ${{ matrix.numpy-version }}
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} numpy=${{ matrix.numpy-version }} cython pip hdf5 libnetcdf cftime
        source activate TEST
        echo [options] > setup.cfg
        echo [directories] >> setup.cfg
        echo HDF5_libdir = $CONDA_PREFIX\\Library\\lib >> setup.cfg
        echo HDF5_incdir = $CONDA_PREFIX\\Library\\include >> setup.cfg
        echo netCDF4_libdir = $CONDA_PREFIX\\Library\\lib >> setup.cfg
        echo netCDF4_incdir = $CONDA_PREFIX\\Library\\include >> setup.cfg
        cat setup.cfg
        pip install -e . --no-deps --force-reinstall

    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        cd test && python run_all.py